# general settings
name: train_HMA_SwinV2_SRx4_win4
model_type: HMAModel
scale: 4
num_gpu: auto
manual_seed: 1234

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /home/projects/datasets/DIV2K/DIV2K_train_HR
    dataroot_lq: /home/projects/datasets/DIV2K/DIV2K_train_LR_bicubic/X4
    filename_tmpl: '{}x4'

    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /home/projects/datasets/TestDataSR/HR/Set14/x4
    dataroot_lq: /home/projects/datasets/TestDataSR/LR/LRBI/Set14/x4
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: GSDATNet
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 8
  interval_size: 4
  img_range: 1.
  depths: [3, 3, 3, 3, 3, 3,]       # 列表长度代表 RHTB 的数量
  num_heads: [6, 6, 6, 6, 6, 6,]
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
#    lr: !!float 5e-6
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
#    milestones: [125000, 200000, 225000, 240000]
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000 #250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3 #!!float 5e3 #
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
#  port: 28500
